version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tricount-rat-front      
    ports:
      - '4000:3000'
    volumes:
      - .:/app
      - /app/node_modules
