import Menu from './components/menu'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        suppressHydrationWarning={true}
      >
        <h1 className="text-4xl mt-20 text-white font-bold dark:text-white text-center">Tricount Rat</h1>
        {children}
        <Menu />
      </body>
    </html>
  )
}
